version: '3.7'
services:
    kong-database:
        container_name: kong-database
        image: postgres:9.6
        restart: unless-stopped
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        networks:
            - kong-lambda-net
    # Uncomment after running the migration.sh
    # kong:
    #     container_name: kong
    #     image: arm64v8/kong:latest
    #     depends_on:
    #         - kong-database
    #     restart: unless-stopped
    #     ports: 
    #         - 8000:8000
    #         - 8443:8443
    #         - 127.0.0.1:8001:8001
    #         - 127.0.0.1:8444:8444
    #     environment: 
    #         KONG_DATABASE: postgres
    #         KONG_PG_HOST: kong-database
    #         KONG_PG_USER: kong
    #         KONG_PG_PASSWORD: kong
    #         KONG_CASSANDRA_CONTACT_POINTS: kong-database
    #         KONG_PROXY_ACCESS_LOG: /dev/stdout
    #         KONG_ADMIN_ACCESS_LOG: /dev/stdout
    #         KONG_PROXY_ERROR_LOG: /dev/stderr
    #         KONG_ADMIN_ERROR_LOG: /dev/stderr
    #         KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
    #     networks:
    #         - kong-lambda-net

networks: 
    kong-lambda-net:
        name: kong-lambda-net
        driver: bridge